@rootURL = http://localhost:5101

GET {{rootURL}}/weatherforecast/
Accept: application/json

###
GET {{rootURL}}/api/books
Accept: application/json
###
GET {{rootURL}}/api/books/2
Accept: application/json

###
POST {{rootURL}}/api/books
Content-Type: application/json

{
    "title": "This is a hell man",
    "author": "Harper Lee",
    "yearPublished": 1930
}

###
PUT {{rootURL}}/api/books/5
Content-Type: application/json

{
  "id":5,
  "title": "Still a hell man",
  "author": "Lee",
  "yearPublished": 1964
}